### ISSUE TITLE
Getting Barrels to play with Passport.js

### ISSUE THREAD

**Issue by Industrial** [bredikhin/barrels#12]
Hi.

I'm trying to fix up some fixtures for the User model. The User model uses the Passport model generated by `https://github.com/kasperisager/sails-generate-auth` (https://gist.github.com/Industrial/e063603eef8d6a456d33).

This is the fixture data:

User.json

``` json
[
  {
    "id":          "1",
    "username":    "BobGod",
    "email":       "bob@test.com",
    "postalCode":  "0000AA",
    "houseNumber": "1",
    "group":       0,
    "passports":   [ 0 ],
    "maxems":      []
  },
  {
    "id":          "2",
    "username":    "SallyAdministrator",
    "email":       "sally@test.com",
    "postalCode":  "0000AA",
    "houseNumber": "1",
    "group":       1,
    "passports":   [ 1 ],
    "maxems":      []
  },
  {
    "id":          "3",
    "username":    "PeterInstaller",
    "email":       "peter@test.com",
    "postalCode":  "0000AA",
    "houseNumber": "1",
    "group":       2,
    "passports":   [ 2 ],
    "maxems":      []
  },
  {
    "id":          "4",
    "username":    "BernieUser",
    "email":       "bernie@test.com",
    "postalCode":  "0000AA",
    "houseNumber": "1",
    "group":       3,
    "passports":   [ 3 ],
    "maxems":      []
  }
]
```

Passport.json

``` json
[
  {
    "id":        "1",
    "protocol":  "local",
    "password":  "bobgod123",
    "user":      0
  },
  {
    "id":        "2",
    "protocol":  "local",
    "password":  "sallyadministrator123",
    "user":      1
  },
  {
    "id":        "3",
    "protocol":  "local",
    "password":  "peterinstaller123",
    "user":      2
  },
  {
    "id":        "4",
    "protocol":  "local",
    "password":  "bernieuser123",
    "user":      3
  }
]
```

and the error:

There's a `required: true` on the user field of the Passport model thaat is throwing this error: https://gist.github.com/Industrial/b7a2ee499a4a58387267

Did I make a mistake somewhere?

gr,

Tom

**Comment by airtonix** [comment]
Am I reading this right? @Industrial has posted an example of fixtures that refer to associated models with zero-index based primaryKeys (first record has primaryKey of 0 rather than 1)...

**Comment by bredikhin** [comment]
Just curious, why would you need fixed ids? 'Cause that's probably the issue here. Also, what's the db?

**Comment by airtonix** [comment]
@bredikhin Habit from using Django and migrations there, (where django would create a contenttype model and not specifying ids led to unexpected results). specifying ids gives assurances that things are as they should be.

Database I'm using is localDisk in development and probably some SQL variant in production as specified by client (mssql in this case)

Just tested this out, and indeed sailsjs (and therefore barrels) actually doesn't use zero index numbering.

Had to specify false as per your example. Fails otherwise.

**Comment by aaronfranco** [comment]
Hi, 

I'm having an issue that relates to this topic. I cannot seem to get Barrels to load my Passport fixtures. I'm getting an unexpected error.

````
1)  "before all" hook:
     Error: the string "No callback function was given." was thrown, throw an Error :)
      at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
````
The Bootstrap for running my tests for SailsJS is as follows.
````
var Sails = require('sails'),
    sails,
    Barrels = require('barrels');

before(function (done) {
    Sails.lift({
        log: {
            level: 'error'
        },
        models: {
            connection: 'test',
            migrate: 'drop'
        }
    }, function (err, server) {
        sails = server;
        if (err) {
            return done(err);
        }

        // here you can load fixtures, etc.
        // Load fixtures
        var barrels = new Barrels();
        var fixtures = barrels.data;

        barrels.populate(['user'], function (err) {
            console.log(err);
            if (err) {
                return done(err); // Higher level callback
            }

            barrels.populate(['passport'], function (err) {
                console.log(err);
                if (err) {
                    return done(err); // Higher level callback
                }
                done(err, sails);
            }, false)
        }, false);
    });
});

after(function (done) {
    // here you can clear fixtures, etc.
    sails.lower(done);
});
````

I cannot figure out why this error is happening. 
My User Fixture looks like this:
````
[
    {
        "id": 1,
        "username": "test",
        "firstName": "bob",
        "lastName": "smith",
        "email": "test@example.com",
        "resetPasswordToken": null,
        "resetPasswordExpires": null
    }
]
````
My Passport Fixture looks like this:
````
[
    {
        "user": 1,
        "protocol": "local",
        "password": "VxknPwc7HC6TVvvBE4Dx"
    }
]
````
My devDependencies:
````
"assert": "^1.3.0",
    "barrels": "^1.4.1",
    "grunt-mocha-istanbul": "^2.4.0",
    "grunt-mocha-test": "^0.12.7",
    "grunt-simple-watch": "^0.1.2",
    "istanbul": "^0.3.13",
    "mocha": "^2.2.4",
    "sails-memory": "^0.10.3",
    "should": "^6.0.1",
    "sinon": "^1.14.1",
    "supertest": "^0.15.0"
````

If I only populate the User model then everything works as expected. But, I always get this error when trying to populate the Passport model. Please let me know if you can help in any way. There must be something I'm missing. 

Best,
Aaron

**Comment by bredikhin** [comment]
Can't really say anything useful based on the error message provided, try it without hardcoding the user `id` though.

**Comment by mikedevita** [comment]
I dont have the userid hard coded, and associations dont auto populate..

**passport.json**

```
[
  {
    "protocol"    : "local",
    "password"    : "1234567890",
    "user"        : 1,
    "accessToken" : "GRDl2v8blOyRay8ss4MIJVoZFEiBw767oobxBMr5w5hVPQ0dtmImkId4wiySeG0l"
  }
]
```

**user.json**
```
[
  {
    "username" : "testuser",
    "email"    : "test@user.com"
  }
]
```

**Comment by mikedevita** [comment]
i just wanted to say, 
removing the `passports` definiton from the `user.json` fixture, and setting the third parameter to `barrels.populate` to `false` fixed my issue..
