### ISSUE TITLE
Faker support

### ISSUE THREAD

**Issue by Globegitter** [bredikhin/barrels#23]
This is more an idea I just had and would certainly be a bigger project, but it would be great to get faker support for automatic data generation.

So you could for example call `var barrels = new Barrels({ faker: true, models: ['user', 'posts'] });`

And then in the `populate` function this would try to call the right faker mehtod. So for example if it finds an `email` property it would create properties via `faker.internet.email();` etc.

Furhtermore it should allow for custom calls, so

``` js
var barrels = new Barrels({ faker: true, models: [
'user': {
  'username': 'internet.email',
  'abstract': 'lorem.words'
},
'posts'
] });
```

Or something similar. I think that would be really awesome to get some populated tests ready within minutes. In fact this `fakerToModel` function would probably even make a good standalone module now that I am writing this down.

In any case, I hope that I will get to this once I find some time myself, just wanted to note it down at an appropriate place.

**Comment by bredikhin** [comment]
First, great idea. Second, as much as I'd like to give people some particular features they request, I'd also prefer to keep things simple. It's actually a good idea for any project, not only for this module.

Anyway, I will be happy to consider any pull requests aiming to implement the solution. Or even before writing any code: if you have some particular use cases where Faker would play nicely with Barrels, please go ahead and share it here.
