### ISSUE TITLE
Please clearly add note regarding the naming form

### ISSUE THREAD

**Issue by apraditya** [bredikhin/barrels#25]
I understand it is stated on the README that the fixture files are named after the model. However, it may still be confusing to some (at least to me) since the [Sails guide](http://sailsjs.org/#!/documentation/concepts/ORM/Models.html) name the model using singular form while some (may be most) people name their fixtures  in plural form for obvious reason. In the README, you mentioned `test/fixtures/products.json` (plural) but no body knows which form your models in.

Also in the [example repo](https://github.com/bredikhin/sailsjs-mocha-testing-barrels-fixtures-example), the model files are in plural forms which is different than the official Sails convention.

It would be nice if the fixtures are in plural and Barrels would just work. In the mean time, I'd use singular form in the fixtures in the so it is consistent with what is stated in the README.

**Comment by IanVS** [comment]
+1, I'm still trying to figure out how to use this, and I'm glad I found this issue because I wouldn't have realized I needed to name my fixture singular.

**Comment by bredikhin** [comment]
I really don't see it as an issue. The only reason behind using plurals was the fact that Sails' blueprints are just sticking the model name to the URL, which makes having them in singular form less RESTful (although using the plural nouns in the URLs is not a standard, I still believe it can be considered a best practice). So, even though traditionally models have to be named in singular form, I guess, in this case it's just the price we have to pay to use the blueprints. In any case, whether your model names are singular or plural, it doesn't really matter, whatever works better for you, just name the fixture files accordingly.

**Comment by IanVS** [comment]
They just have to be the same for barrels to work correctly, right?

**Comment by bredikhin** [comment]
Yep.
