### ISSUE TITLE
is there a way to specify populate everything except

### ISSUE THREAD

**Issue by mikedevita** [bredikhin/barrels#26]
basically, as it stands (using your passport/user example) I have to populate Users first, and then everything else.. 

this requires you to explicitly define all of the other models, a bit of a pain if you're not used to it and just banging out new features.. such like..

```javascript
barrels.populate(['user'], function(err) {
  if (err)
    return done(err); // Higher level callback

  // Users will already be populated here, so the required association should work
  barrels.populate(['passport', 'comment', 'location', 'log', 'tag'], function(err) {
    if (err)
      return done(err); // Higher level callback

      // Do your thing...
      done();
    });
  });
```

Is it possible to add some logic in, (if it already hasn't) that would allow something like this..

```javascript
barrels.populate(['user'], function(err) {
  if (err)
    return done(err); // Higher level callback

  // Users will already be populated here, so the required association should work
  barrels.populate(function(err) {
    if (err)
      return done(err); // Higher level callback

      // Do your thing...
      done();
    });
  });
```

barrels would then look at whats already populated, and only populate everything else..

**Comment by bredikhin** [comment]
Interesting, seems like a handy feature. Not sure though if it makes sense to complicate the API this far: `Object.keys(barrels.data)` gives you a list of model names, and you can easily exclude those that are already loaded.
