### ISSUE TITLE
Model's Capital Attribute - Nulled attr after populating the DB

### ISSUE THREAD

**Issue by OmarTrigui** [bredikhin/barrels#30]
I have used Barrels to populate my MongoDB Database ( via Waterline ORM )
Let's suppose that we have an association between my two models (Collections) via the attr "xattr".

While populating the DB using the prepared fixtures, i get the document "xattr" nulled when it's not capital,
but filled et converted into an ObjectId when it's capitalized ...

Is it a bug, or can i get more details about this problem ?
Thanx

**Comment by bredikhin** [comment]
First time I hear. Can you post some examples of your models and fixture files?

**Comment by OmarTrigui** [comment]
**Models :**

>Feed.js
module.exports = {
  attributes: {
    rss: { // <= Works only (Not null after populating) if 'R' is uppercase 
      model: 'Rss'
    }
 }
 }

-----------------------------
>Rss.js
>module.exports = {
  attributes: {
    data: {
      model: 'Data'
    }
  }
  }
  
-------------------------------

**Fixtures :**

>Feed
[
  {
    "_id": "ObjectId('5592b54dc8dc55eb59788ab3')",
    "rss": "5592b54dc8dc55eb59788ab2",
    "createdAt": "ISODate('2015-06-30T15:27:09.518Z')",
    "updatedAt": "ISODate('2015-06-30T15:27:09.518Z')"
  }
]

-------------------------------------

>Rss
[
  {
    "_id": "ObjectId('5592b54dc8dc55eb59788ab2')",
    "data": "ObjectId('5592b54dc8dc55eb59788ab1')",
    "createdAt": "ISODate('2015-06-30T15:27:09.269Z')",
    "updatedAt": "ISODate('2015-06-30T15:27:09.269Z')"
  }
]

**Comment by bredikhin** [comment]
According to the [Sails' docs](http://sailsjs.org/documentation/concepts/models-and-orm/associations/one-to-many#?onetomany-example), your model should be all lowercase. Also, if these fixtures are the contents of your JSON files, you shouldn't hardcode the ids, as well as the timestamps, Mongo will do it for you. And association mapping can be done using the position in your fixture file (which is just 1 for your example).

**Comment by OmarTrigui** [comment]
The hardcoded ids/timestamps in the JSON files are used only for particular testing purposes.
Models start with lowercase, you may check the [Models](http://sailsjs.org/documentation/concepts/models-and-orm/models) in the official Sails' docs.

**Comment by bredikhin** [comment]
I was talking about

```javascript
rss: {
  model: 'rss'
}
```
part.

**Comment by OmarTrigui** [comment]
Exactly, that's the main goal of submitting this issue, if the rss attribute starts with a lowercase, it will be null after populating the DB, but if the attr starts with Uppercase, it will get the right id (Right mapping).

*After populating the DB :*

In the model, if the attribute starts with Lowercase 'r'ss
>{"_id": "ObjectId('5592b54dc8dc55eb59788ab3')",
>"rss": null,
>"createdAt": "ISODate('2015-06-30T15:27:09.518Z')",
>"updatedAt": "ISODate('2015-06-30T15:27:09.518Z')}"

------


In the model, if the attribute starts with Uppercase 'R'ss
>{"_id": ObjectId('5592b54dc8dc55eb59788ab3'),
>"rss": ObjectId('8dc5552b54d975bceb53988a'),
>"createdAt": "ISODate('2015-06-30T15:21:19.518Z')",
>"updatedAt": "ISODate('2015-06-30T15:21:19.518Z')}"

Thanx anyway.
